### PR TITLE
Fix variable names in GitHub actions config

### PR DESCRIPTION
**Pull request by iamthad**
Commit 5fd1bdd7fc501d1a94dcedf80ec539f696deaf3f renamed some CMake variables from `WHISPER_SUPPORT_*` to `WHISPER_*`, but the GitLab Actions config still has the old names.

As a result, the "OpenBLAS-enabled" Windows builds don't actually enable BLAS support.

### CODE REVIEW

**Comment by bobqianic** [comment]
Nice find! So, this PR reinstates several sanity checks and reveals quite a few problems in the current master branch.

**Comment by bobqianic** [comment]
Could you also refresh the OpenBLAS download link to ensure it's the latest version?

For reference, please check: [OpenBLAS Releases on GitHub](https://github.com/OpenMathLib/OpenBLAS/releases).

image

**Comment by iamthad** [comment]
I've added a commit that renames the `blasdir` variable in `build.yml` to `OPENBLAS_PATH`, as introduced in #1128. This should fix the ["Environment variable OPENBLAS_PATH not defined" error](https://github.com/ggerganov/whisper.cpp/actions/runs/6777812801/job/18422298587#step:6:31) in the build.

**Comment by bobqianic** [comment]
Do you have any suggestions for a fix? [error C2039: 'n_gpu_layers': is not a member of 'llama_context_params'](https://github.com/ggerganov/whisper.cpp/actions/runs/6778208145/job/18423427560#step:6:516) @jhen0409

**Comment by jhen0409** [comment]
> Do you have any suggestions for a fix? [error C2039: 'n_gpu_layers': is not a member of 'llama_context_params'](https://github.com/ggerganov/whisper.cpp/actions/runs/6778208145/job/18423427560#step:6:516) @jhen0409
> 
> #1436
> 
> https://github.com/ggerganov/whisper.cpp/blob/0463028bc2a5774fe7361c8ac37bef440725bcd7/examples/talk-llama/talk-llama.cpp#L279-L281

Ahh I think it may be wrong, `n_gpu_layers` should be used in lmparams.

**Review by ggerganov — APPROVED** [review]
