### ISSUE TITLE
Link error with latest version

### ISSUE THREAD

**Issue by RndyP** [ggerganov/whisper.cpp#1222]
Visual studio 2022

1>Whisper.obj : error LNK2019: unresolved external symbol ggml_cpu_has_ssse3 referenced in function whisper_print_system_info

**Comment by przemoc** [comment]
For such reports to be actionable you need to provide a bit more information. Always provide commit id you're using ("latest" is relative term and as time goes on, it stops becoming the latest) and what you're doing exactly.

SSSE3 availability detection during ggml compilation has been introduced in commit 601c2d2181d4, and it's not different from similar detection that was available earlier for other x86 ISA extensions.

It looks like you tried to link whisper after rebuilding whisper.cpp, but not rebuilding ggml.c prior to that. But I do not use Visual Studio, so I may be wrong here.

**Comment by RndyP** [comment]
Sorry for being so terse. Someone forgot to add:

int ggml_cpu_has_ssse3(void) {
#if defined(__SSSE3__)
    return 1;
#else
    return 0;
#endif
}

to ggml.c

Not sure why non-Visual studio users aren't seeing this.

**Comment by RndyP** [comment]
Fixed. Thanks!
