### ISSUE TITLE
Clang error during build

### ISSUE THREAD

**Issue by tazz4843** [ggerganov/whisper.cpp#113]
Hi there! I'm trying to generate bindings with `rust-bindgen`, and Clang is throwing an error that prevents me from doing so. 
```
./whisper.cpp/whisper.h:131:17: error: must use 'struct' tag to refer to type 'whisper_token_data'
```
It looks like this was introduced in 85d6e1e1e73af16c5bfe4b47c2301b1849bee2d7, as its parent is the last commit that works to generate bindings.
